version: '3.7'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    # REDIS_HOST: localhost

  api:
    build: .
    restart: always
    ports:
      - 8000:8000
    environment:
      MYSQL_DATABASE: tarpaulin
      MYSQL_USER: squid
      MYSQL_PASSWORD: squid
      MYSQL_ROOT_PASSWORD: squid
      MYSQL_HOST: mysql
      REDIS_HOST: redis

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: tarpaulin
      MYSQL_USER: squid
      MYSQL_PASSWORD: squid
      MYSQL_ROOT_PASSWORD: squid